# generated by Git for Windows
[ -f ~/.profile ] && . ~/.profile
[ -f ~/.bashrc ] && . ~/.bashrc

# Prompt
export PS1="\[\e[0;35m\]\u@\h\[\e[0m\]:\[\e[0;33m\]\w\[\e[0m\]\n\\$ "

# Path
DOT_FILES="${HOME}/dotfiles"
export PATH="${PATH}:${DOT_FILES}"

# tmux
case $(uname -o | tr '[:upper:]' '[:lower:]') in
msys*)
  # Windows
  tmux source "${DOT_FILES}/.tmux.conf"
  [ $SHLVL = 1 ] && tmux
  break
  ;;
*)
  break
  ;;
esac

alias ide="sh '${DOT_FILES}/commands/ide.sh'"
