# ============================================================================
# BASH PROFILE CONFIGURATION
# ============================================================================

# ----------------------------------------
# Source Configuration Files
# ----------------------------------------
# Generated by Git for Windows
[ -f ~/.profile ] && . ~/.profile
[ -f ~/.bashrc ] && . ~/.bashrc

# ----------------------------------------
# Prompt Configuration
# ----------------------------------------
export PS1="\[\e[0;35m\]\u@\h\[\e[0m\]:\[\e[0;33m\]\w\[\e[0m\]\n\\$ "

# ----------------------------------------
# Path Configuration
# ----------------------------------------
DOT_FILES="${HOME}/dotfiles"
export PATH="${PATH}:${DOT_FILES}"
# Remove duplicate entries
export PATH=$(echo $PATH | awk -v RS=: -v ORS=: '!($0 in a) {a[$0]; print}' | sed 's/:$//')

# ----------------------------------------
# Tmux Configuration
# ----------------------------------------
case $(uname -o 2>/dev/null || uname -s | tr '[:upper:]' '[:lower:]') in
  msys* | mingw* | cygwin*)
    # Windows environment
    tmux source "${HOME}/.tmux.conf" 2>/dev/null || tmux source "${DOT_FILES}/tmux/.tmux.conf" 2>/dev/null
    # Auto-start tmux at login shell level
    [ $SHLVL = 1 ] && tmux
    ;;
esac

# ----------------------------------------
# Aliases
# ----------------------------------------
alias ide="sh '${DOT_FILES}/commands/ide.sh'"
alias grep="grep --color=auto"
