version: "3.7"
services:
  frontend:
    container_name: frontend
    restart: always
    build: frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - react-express
    stdin_open: true
    # ports:
    #   - 3000:3000

  backend:
    container_name: backend
    restart: always
    build: backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    secrets:
      - db-password
    depends_on:
      - mongo
      - mysql
    networks:
      - express-mongo
      - express-mysql
      - react-express
    # expose:
    #   - 3000
  mysql:
    # https://github.com/docker/awesome-compose/blob/master/nginx-golang-mysql
    container_name: mysql
    restart: always
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
  mongo:
    # https://github.com/docker/awesome-compose/tree/master/react-express-mongodb
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017

  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - react-express

volumes:
  db-data:
secrets:
  db-password:
    file: mysql/password.txt
networks:
  react-express:
  express-mysql:
  express-mongo:
